VIA_ENABLE = yes
VIAL_ENABLE = yes

EXTRAFLAGS += -flto

KEY_LOCK_ENABLE = no
MOUSEKEY_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
LTO_ENABLE = yes
EXTRAKEY_ENABLE = no
RGBLIGHT_ENABLE = no
BOOTMAGIC_ENABLE = no